// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZcwMcgvFtmdvuuoQR4rPERCvPe_Zf0VE',
    appId: '1:751546397442:web:b731070b6f8c26a818481b',
    messagingSenderId: '751546397442',
    projectId: 'myapp-31112',
    authDomain: 'myapp-31112.firebaseapp.com',
    storageBucket: 'myapp-31112.appspot.com',
    measurementId: 'G-ZJNSW2F4NR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWr7hQCvj3woHbqvq_Jl-FjFktmgWB08o',
    appId: '1:751546397442:android:2b4fb5c9c9c1554818481b',
    messagingSenderId: '751546397442',
    projectId: 'myapp-31112',
    storageBucket: 'myapp-31112.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk4j0yi8siywzbfiw0tlmSscSLTWp4JBg',
    appId: '1:751546397442:ios:b3dbbbf055c8374018481b',
    messagingSenderId: '751546397442',
    projectId: 'myapp-31112',
    storageBucket: 'myapp-31112.appspot.com',
    iosClientId: '751546397442-mh22is4skolhfrirni1emngu2vnju1vb.apps.googleusercontent.com',
    iosBundleId: 'com.example.pruebafinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk4j0yi8siywzbfiw0tlmSscSLTWp4JBg',
    appId: '1:751546397442:ios:b3dbbbf055c8374018481b',
    messagingSenderId: '751546397442',
    projectId: 'myapp-31112',
    storageBucket: 'myapp-31112.appspot.com',
    iosClientId: '751546397442-mh22is4skolhfrirni1emngu2vnju1vb.apps.googleusercontent.com',
    iosBundleId: 'com.example.pruebafinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZcwMcgvFtmdvuuoQR4rPERCvPe_Zf0VE',
    appId: '1:751546397442:web:8d58f2e2474c5eaa18481b',
    messagingSenderId: '751546397442',
    projectId: 'myapp-31112',
    authDomain: 'myapp-31112.firebaseapp.com',
    storageBucket: 'myapp-31112.appspot.com',
    measurementId: 'G-64VYZET58G',
  );
}
