// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEghkYUL0CgcoSpQwEI6p1REqLEQey7Fw',
    appId: '1:722696644188:web:626ba881dafee9484be899',
    messagingSenderId: '722696644188',
    projectId: 'prueba1-dfe98',
    authDomain: 'prueba1-dfe98.firebaseapp.com',
    storageBucket: 'prueba1-dfe98.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBsbhbXVvt5kDiaxmSH8_mFkVFVzLVk9w',
    appId: '1:722696644188:android:3f99253c965d10bb4be899',
    messagingSenderId: '722696644188',
    projectId: 'prueba1-dfe98',
    storageBucket: 'prueba1-dfe98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvmSs0wLCqRXlzz4zGb5jE31GgavFHsFc',
    appId: '1:722696644188:ios:b81752c02c617c4b4be899',
    messagingSenderId: '722696644188',
    projectId: 'prueba1-dfe98',
    storageBucket: 'prueba1-dfe98.appspot.com',
    iosClientId: '722696644188-d6rfetluk21dl9dcr7n21sb1ggjvm815.apps.googleusercontent.com',
    iosBundleId: 'com.example.pruebafinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvmSs0wLCqRXlzz4zGb5jE31GgavFHsFc',
    appId: '1:722696644188:ios:b81752c02c617c4b4be899',
    messagingSenderId: '722696644188',
    projectId: 'prueba1-dfe98',
    storageBucket: 'prueba1-dfe98.appspot.com',
    iosClientId: '722696644188-d6rfetluk21dl9dcr7n21sb1ggjvm815.apps.googleusercontent.com',
    iosBundleId: 'com.example.pruebafinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEghkYUL0CgcoSpQwEI6p1REqLEQey7Fw',
    appId: '1:722696644188:web:4909e5cf6ccf501c4be899',
    messagingSenderId: '722696644188',
    projectId: 'prueba1-dfe98',
    authDomain: 'prueba1-dfe98.firebaseapp.com',
    storageBucket: 'prueba1-dfe98.appspot.com',
  );

}